### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by LankyWhisper624**

### CODE REVIEW

**Review by ielenia — CHANGES_REQUESTED** [review]
Maybe each one should indicate to users that they should delete the text with the descriptions

**Review by ielenia — APPROVED** [review]

**Review by ielenia — COMMENTED** [review]
feature request needs updated

**Review by ielenia — CHANGES_REQUESTED** [review]
Update FR temp

**Review by ielenia — APPROVED** [review]
Everything should be good now

**Comment by LankyWhisper624** [comment]
merging...

**Pull request merged**
